spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://mongodb:27017/geolocation
server:
  port: 8081  # Si está aquí, cámbialo a 8081 o elimínalo